### ISSUE TITLE
music lib name an HepMC

### ISSUE THREAD

**Issue by dongjokim** [JETSCAPE/JETSCAPE#35]
Hello

I found that i need to change the name of music lib in.
src/CMakeLists.txt : need to be changed : 
 if ( music )
-  target_link_libraries (JetScape music_lib )
+  target_link_libraries (JetScape music )
 endif()

and also wondering if HepMCdata writing can be fixed sooner or later.

Cheers,

DongJo

**Comment by jdmulligan** [comment]
Hi DongJo,

Thanks for your report!
This will be fixed in the upcoming release (couple weeks).

I am not exactly sure what you mean by HepMC data writing -- this functionality should be working. What is the problem you encounter?
Note also that in the upcoming release we will switch to use HepMC >=3.1 exclusively, which will avoid system conflicts between HepMC2 and HepMC3.

Best,
James

**Comment by dongjokim** [comment]
Hi, James
Thanks for your prompt reply.
HEPMC was disabled as a default.
Once i enabled in CMakeList, i am getting the following errors.
any idea? i am working with HepMC3-3.2.0.

........
[ 91%] Built target hydroJetTestPGun
CMakeFiles/PythiaBrickTest.dir/examples/PythiaBrickTest.cc.o: In function `Jetscape::JetScapeWriterHepMC::JetScapeWriterHepMC(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/n/work00/software/jetscape/JETSCAPE/./src/framework/JetScapeWriterHepMC.h:45: undefined reference to `HepMC::WriterAscii::WriterAscii(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<HepMC::GenRunInfo>)'
collect2: error: ld returned 1 exit status
make[2]: *** [PythiaBrickTest] Error 1
make[1]: *** [CMakeFiles/PythiaBrickTest.dir/all] Error 2
CMakeFiles/hydroJetTest.dir/examples/hydroJetTest.cc.o: In function `Jetscape::JetScapeWriterHepMC::JetScapeWriterHepMC(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/n/work00/software/jetscape/JETSCAPE/./src/framework/JetScapeWriterHepMC.h:45: undefined reference to `HepMC::WriterAscii::WriterAscii(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<HepMC::GenRunInfo>)'
collect2: error: ld returned 1 exit status
make[2]: *** [hydroJetTest] Error 1
make[1]: *** [CMakeFiles/hydroJetTest.dir/all] Error 2

Regards,

DongJo

**Comment by jdmulligan** [comment]
Hi DongJo,

The problem is that starting in HepMC 3.1 they [changed quite a bit of the internal structure](http://hepmc.web.cern.ch/hepmc/differences.html). The current Jetscape release will unfortunately only work with HepMC 3.0 (this is poorly documented, apologies -- fixes coming soon). 

So there are a few options:
- Install HepMC 3.0
- [Install JETSCAPE using Docker](https://github.com/JETSCAPE/JETSCAPE/tree/master/docker) (I recommend this option -- this is currently our main solution to avoid problems with the dependencies)
- Wait for the new release in a couple weeks, which will work with any HepMC >= 3.1. 

Please let me know if you have any further issues.

Best,
James

**Comment by dongjokim** [comment]
thanks, I will wait for the update.

Cheers,

DongJo

**Comment by jdmulligan** [comment]
Fixed in new release JETSCAPE 3.0
