### ISSUE TITLE
issues installing w/ external packages and compiling/running custom examples 

### ISSUE THREAD

**Issue by rkunnawa** [JETSCAPE/JETSCAPE#48]

**Comment by rkunnawa** [comment]
ohh whoops! Sorry i clicked enter without submitting the text part! doing that here -

**Comment by rkunnawa** [comment]
Im installing it on a linux system with all the prerecs installed. i have gcc version 7.3.

1. the first issue i have is with smash. i installed pythia 8.235 and i get the error upon running make - 
`[ 68%] Building CXX object src/CMakeFiles/objlib.dir/listmodus.cc.o
[ 68%] Building CXX object src/CMakeFiles/objlib.dir/logging.cc.o
In file included from /wsu/el7/gnu7/root/6.14.06/include/TString.h:28:0,
                 from /wsu/el7/gnu7/root/6.14.06/include/TNamed.h:26,
                 from /wsu/el7/gnu7/root/6.14.06/include/TDirectory.h:25,
                 from /wsu/el7/gnu7/root/6.14.06/include/TDirectoryFile.h:24,
                 from /wsu/el7/gnu7/root/6.14.06/include/TFile.h:26,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/rootoutput.h:18,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/experiment.h:42,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/experiment.cc:10:
/wsu/el7/gnu7/root/6.14.06/include/ROOT/RStringView.hxx:67:17: error: expected type-specifier
        operator std::string_view() const { return std::string_view(fData,fLength); }
                 ^~~
In file included from /wsu/el7/gnu7/root/6.14.06/include/TNamed.h:26:0,
                 from /wsu/el7/gnu7/root/6.14.06/include/TDirectory.h:25,
                 from /wsu/el7/gnu7/root/6.14.06/include/TDirectoryFile.h:24,
                 from /wsu/el7/gnu7/root/6.14.06/include/TFile.h:26,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/rootoutput.h:18,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/experiment.h:42,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/experiment.cc:10:
/wsu/el7/gnu7/root/6.14.06/include/TString.h:110:13: error: expected type-specifier
    operator std::string_view() const { return std::string_view(Data(),fExtent); }
             ^~~
/wsu/el7/gnu7/root/6.14.06/include/TString.h:275:23: error: ‘string_view’ in namespace ‘std’ does not name a type
    TString(const std::string_view &sub);
                       ^~~~~~~~~~~
/wsu/el7/gnu7/root/6.14.06/include/TString.h:312:37: error: ‘string_view’ in namespace ‘std’ does not name a type
    TString    &operator=(const std::string_view &s);
                                     ^~~~~~~~~~~
/wsu/el7/gnu7/root/6.14.06/include/TString.h:439:9: error: ‘string_view’ in namespace ‘std’ does not name a type
    std::string_view View() const { return std::string_view(GetPointer(),Length()); }
         ^~~~~~~~~~~
In file included from /wsu/el7/gnu7/root/6.14.06/include/TNamed.h:26:0,
                 from /wsu/el7/gnu7/root/6.14.06/include/TDirectory.h:25,
                 from /wsu/el7/gnu7/root/6.14.06/include/TDirectoryFile.h:24,
                 from /wsu/el7/gnu7/root/6.14.06/include/TFile.h:26,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/rootoutput.h:18,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/experiment.h:42,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/experiment.cc:10:
/wsu/el7/gnu7/root/6.14.06/include/TString.h:834:53: error: ‘string_view’ in namespace ‘std’ does not name a type
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                     ^~~~~~~~~~~
/wsu/el7/gnu7/root/6.14.06/include/TString.h:834:68: error: ‘Bool_t operator==(const char*, const int&)’ must have an argument of class or enumerated type
 inline Bool_t operator==(const char *s1, const std::string_view &s2)
                                                                    ^
/wsu/el7/gnu7/root/6.14.06/include/TString.h:839:37: error: ‘string_view’ in namespace ‘std’ does not name a type
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                     ^~~~~~~~~~~
/wsu/el7/gnu7/root/6.14.06/include/TString.h:839:68: error: ‘Bool_t operator==(const int&, const char*)’ must have an argument of class or enumerated type
 inline Bool_t operator==(const std::string_view &s1, const char *s2)
                                                                    ^
/wsu/el7/gnu7/root/6.14.06/include/TString.h:852:37: error: ‘string_view’ in namespace ‘std’ does not name a type
   std::string printValue(const std::string_view* val);
                                     ^~~~~~~~~~~
In file included from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/rootoutput.h:18:0,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/experiment.h:42,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/experiment.cc:10:
/wsu/el7/gnu7/root/6.14.06/include/TFile.h:318:45: error: ‘std::string_view’ has not been declared
    static Bool_t       SetCacheFileDir(std::string_view cacheDir, Bool_t operateDisconnected = kTRUE,
                                             ^~~~~~~~~~~
/wsu/el7/gnu7/root/6.14.06/include/TFile.h: In static member function ‘static Bool_t TFile::SetCacheFileDir(ROOT::Internal::TStringView, Bool_t, Bool_t)’:
/wsu/el7/gnu7/root/6.14.06/include/TFile.h:317:36: error: ‘string_view’ is not a member of ‘std’
      { return SetCacheFileDir(std::string_view(cacheDir), operateDisconnected, forceCacheread); }
                                    ^~~~~~~~~~~
/wsu/el7/gnu7/root/6.14.06/include/TFile.h:317:36: note: suggested alternative: ‘stringstream’
      { return SetCacheFileDir(std::string_view(cacheDir), operateDisconnected, forceCacheread); }
                                    ^~~~~~~~~~~
                                    stringstream
[ 71%] Building CXX object src/CMakeFiles/objlib.dir/nucleus.cc.o
[ 71%] Building CXX object src/CMakeFiles/objlib.dir/oscaroutput.cc.o
[ 71%] Building CXX object src/CMakeFiles/objlib.dir/pauliblocking.cc.o
[ 71%] Building CXX object src/CMakeFiles/objlib.dir/parametrizations.cc.o
[ 75%] Building CXX object src/CMakeFiles/objlib.dir/particledata.cc.o
[ 75%] Building CXX object src/CMakeFiles/objlib.dir/particles.cc.o
[ 75%] Building CXX object src/CMakeFiles/objlib.dir/particletype.cc.o
make[3]: *** [src/CMakeFiles/objlib.dir/build.make:333: src/CMakeFiles/objlib.dir/experiment.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 78%] Building CXX object src/CMakeFiles/objlib.dir/pdgcode.cc.o
make[2]: *** [CMakeFiles/Makefile2:1518: src/CMakeFiles/objlib.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:1573: src/CMakeFiles/smash_shared.dir/rule] Error 2
make: *** [Makefile:682: smash_shared] Error 2
[gp1574@rhi3 build]$ 
`
This seems like an issue with a particular root version? (it have the same version as the one the instructions point to)

2. Now if i just ignore the smash for now and get all the other packages and get music, iSS and freestream and clvisc (no issues in getting them) and cmake and finally make with turning them on
i get the following error during the cmake 
`Includes for freestream ...
-- Could NOT find OpenCL (missing: OPENCL_LIBRARIES OPENCL_INCLUDE_DIRS) '
and the following error during make 
`[ 81%] Building CXX object src/CMakeFiles/JetScape.dir/hydro/GubserHydro.cc.o
In file included from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/src/hydro/CLViscWrapper.cc:24:0:
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/src/hydro/CLViscWrapper.h:20:10: fatal error: clvisc.h: No such file or directory
 #include "clvisc.h"
          ^~~~~~~~~~
compilation terminated.
`

**Comment by rkunnawa** [comment]
Jetscape compiles and i can run the default examples without any issue if i only include music and iSS as the external package. 
Im interested in running the two stage hydro example and when i include that in the executables area of the CMakeLists.txt and run make, i get the following error  -

> [ 98%] Built target LiquifierBase
In file included from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/x86_64-pc-linux-gnu/bits/c++allocator.h:33:0,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/allocator.h:46,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/string:41,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/locale_classes.h:40,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/ios_base.h:41,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/ios:42,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/ostream:38,
                 from /opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/iostream:39,
                 from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/examples/TwoStagesHydro.cc:21:
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = Jetscape::JetScape; _Args = {const char (&)[20], int}; _Tp = Jetscape::JetScape]’:
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/alloc_traits.h:475:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = Jetscape::JetScape; _Args = {const char (&)[20], int}; _Tp = Jetscape::JetScape; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<Jetscape::JetScape>]’
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/shared_ptr_base.h:526:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {const char (&)[20], int}; _Tp = Jetscape::JetScape; _Alloc = std::allocator<Jetscape::JetScape>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/shared_ptr_base.h:637:4:   required from ‘std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = Jetscape::JetScape; _Alloc = std::allocator<Jetscape::JetScape>; _Args = {const char (&)[20], int}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/shared_ptr_base.h:1295:35:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<Jetscape::JetScape>; _Args = {const char (&)[20], int}; _Tp = Jetscape::JetScape; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/shared_ptr.h:344:64:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<Jetscape::JetScape>; _Args = {const char (&)[20], int}; _Tp = Jetscape::JetScape]’
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/shared_ptr.h:690:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = Jetscape::JetScape; _Alloc = std::allocator<Jetscape::JetScape>; _Args = {const char (&)[20], int}]’
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/bits/shared_ptr.h:706:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = Jetscape::JetScape; _Args = {const char (&)[20], int}]’
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/examples/TwoStagesHydro.cc:82:65:   required from here
/opt/ohpc/pub/compiler/gcc/7.3.0/include/c++/7.3.0/ext/new_allocator.h:136:4: error: no matching function for call to ‘Jetscape::JetScape::JetScape(const char [20], int)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/examples/TwoStagesHydro.cc:25:0:
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/./src/framework/JetScape.h:31:3: note: candidate: Jetscape::JetScape::JetScape()
   JetScape();
   ^~~~~~~~
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/./src/framework/JetScape.h:31:3: note:   candidate expects 0 arguments, 2 provided
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/./src/framework/JetScape.h:26:7: note: candidate: Jetscape::JetScape::JetScape(const Jetscape::JetScape&)
 class JetScape : public JetScapeModuleBase {
       ^~~~~~~~
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/./src/framework/JetScape.h:26:7: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/TwoStagesHydro.dir/build.make:63: CMakeFiles/TwoStagesHydro.dir/examples/TwoStagesHydro.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:122: CMakeFiles/TwoStagesHydro.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX executable hydroJetTestPGun
[ 98%] Built target hydroJetTestPGun
make: *** [Makefile:130: all] Error 2
[gp1574@rhi3 build]$

**Comment by rkunnawa** [comment]
Also TwoStateHydroFromFile has an additional issue which seems like a simple typo? 
`/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/examples/TwoStagesHydroFromFile.cc: In function ‘int main(int, char**)’:
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/examples/TwoStagesHydroFromFile.cc:111:10: error: ‘using element_type = class Jetscape::JetEnergyLoss {aka class Jetscape::JetEnergyLoss}’ has no member named ‘add_a_liqueifier’; did you mean ‘add_a_liquefier’?
   jloss->add_a_liqueifier(myliquefier);
          ^~~~~~~~~~~~~~~~
          add_a_liquefier
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/examples/TwoStagesHydroFromFile.cc:130:11: error: ‘using element_type = class MpiMusic {aka class MpiMusic}’ has no member named ‘add_a_liqueifier’; did you mean ‘add_a_liquefier’?
   hydro2->add_a_liqueifier(myliquefier);
           ^~~~~~~~~~~~~~~~
`

**Comment by jdmulligan** [comment]
Hi Raghav, 

Thanks for the reports :)

1. I'm not immediately sure what causes this -- to confirm, this error only happens when you build with SMASH? Following the instructions [here](https://github.com/JETSCAPE/JETSCAPE/tree/master/external_packages#smash-hadronic-afterburner)? @doliinychenko any thoughts?
2. OpenCL is a pre-requisite for CLVisc (see [here](https://github.com/JETSCAPE/JETSCAPE/tree/master/external_packages#smash-hadronic-afterburner)), so you will need that installed in order to use CLVisc (can admittedly be a bit of a pain to install on linux). 
3. I personally would recommend that you don't build any executables, but rather use the "new" way of running JETSCAPE outlined in the current documentation (updated with the. 3.0 release). There is an example two-stage hydro configuration that you can run with: `runJetscape ../config/jetscape_user_twostagehydro.xml`, which you can adjust as desired.

**Comment by rkunnawa** [comment]
Ahh! I love this new interface, its a cool idea! it seems to work and theres a bunch of output and finished with a bunch of onscreen output (which im not sure is correct or not) and some output files. time to play with them :) 
```
....
Sampling finished in 0 seconds.
🎵 465.8 MB Index: 265, Name: Anti-Lambda2110, Monte-carlo index: -23126

 -- calculate_dN_dxtdy_for_one_particle_species finished in 0 seconds.
🎵 465.8 MB  -- Sampling using dN_dy=0.00023644, dN=0.00023644...

Sampling finished in 0 seconds.
🎵 465.8 MB Index: 266, Name: Lambda2110, Monte-carlo index: 23126

 -- calculate_dN_dxtdy_for_one_particle_species finished in 0 seconds.
🎵 465.8 MB  -- Sampling using dN_dy=0.00023644, dN=0.00023644...

Sampling finished in 0 seconds.

sample_using_dN_dxtdy_4all_particles finished in 0.21 seconds.
perform resonance decays... 
Error:particleSamples::perform_two_body_decay:can not found decays!
M = 0.783, m1 = 0.138, m2 = 0.776
```  

Regarding smash - yes i was following the instructions. 

Regarding OpenCL - Yeah thats what i figured. I contacted our grid folks to see if we can get that installed centrally. thanks!

**Comment by doliinychenko** [comment]
Either SMASH got updated and wants a newer pythia version or you have have more than one pythia installed and this creates a conflict. For the latter case check your cmake output concerning pythia: does it find the one you expect it to find?

**Comment by doliinychenko** [comment]
Oh, I looked at your errors again, pythia is not a problem. ROOT seems to generate some trouble. I don't know if ROOT is backward compatible, but SMASH was working with ROOT 6.14 before. I personally prefer ROOT 5.34, because it is a much smaller beast and I don't need any newer functionality anyways.

**Comment by doliinychenko** [comment]
`error: 'string_view' is not a member of 'std'`

The problem here is that newest ROOT is relying on C++17 (not a great idea, but not really a bug too). SMASH is compiled by default with c++11 flag, so string_view is just not found in the standard library. Maybe the issue will be resolved if you go to smash CmakeLists.txt and change c++11 to c++17. However, I don't think this was tested before and may create new problems.

**Comment by rkunnawa** [comment]
Ah i see. ok thanks for the follow up @doliinychenko. There are further issues that pop up when i compile it with c+1z regarding overloaded function calls 
here is one for example 
```
/tier2/home/groups/rhi/STAR/software/JETSCAPE_v3/external_packages/smash/smash_code/src/include/smash/modusdefault.h:176:73: error: call of overloaded ‘make_unique<smash::GrandCanThermalizer>(smash::Configuration&, const std::array<double, 3>&, const std::array<double, 3>&, const bool&)’ is ambiguous
     return make_unique<GrandCanThermalizer>(conf, l, origin, periodicity);
```
In any case, i will leave smash as is and play the ones i have working :)

**Comment by doliinychenko** [comment]
I can see, how the make_unique problem is emerging. SMASH introduces its own make_unique, which is just a port from c++14. But then when you switch on the c++17, there are two make_unique functions now: one in SMASH and one in the standard library.
